#!/usr/bin/env bash

__deezer() {
    local DEEZER_HOME=$HOME/.deezerloadermix
    local DIR_ORIGINAL=$(pwd)
    local BANNER="ICBfXyBcICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICB8ICAgICAgICAgICAgICAgICAgICAgICAgfCAgICAgICAgICAgICAgIF8gXCAgICAgICAgICAgICAgICAgICBfKSAgICAgICAgCiAgfCAgIHwgICBfIFwgICBfIFwgXyAgLyAgIF8gXCAgIF9ffCAgfCAgICAgICBfIFwgICAgX2AgfCAgIF9gIHwgICBfIFwgICBfX3wgIHwgICB8ICAgXyBcICBfXyBgX18gXCAgIHwgXCBcICAvIAogIHwgICB8ICAgX18vICAgX18vICAgLyAgICBfXy8gIHwgICAgIHwgICAgICAoICAgfCAgKCAgIHwgICggICB8ICAgX18vICB8ICAgICBfXyA8ICAgIF9fLyAgfCAgIHwgICB8ICB8ICBgICA8ICAKIF9fX18vICBcX19ffCBcX19ffCBfX198IFxfX198IF98ICAgIF9fX19ffCBcX19fLyAgXF9fLF98IFxfXyxffCBcX19ffCBffCAgICBffCBcX1wgXF9fX3wgX3wgIF98ICBffCBffCAgXy9cX1wgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIA=="
    
    if [ -d "$DEEZER_HOME" ]; then
        echo $BANNER | base64 -d
        echo
        cd "$DEEZER_HOME" && npm start
        cd "$DIR_ORIGINAL"
    else
        echo "no found Directory"
    fi
}

# __deezer


